s:\(import antlr.ANTLRException;\):/* \1 */:
s:\(import antlr.CharScanner;\):/* \1 */:
s:\(import antlr.CommonToken;\):/* \1 */:
s:\(import antlr.MismatchedCharException;\):/* \1 */:
s:\(import antlr.SemanticException;\):/* \1 */:
s:\(import frysk.value.*;\):/* \1 */:
s:\(import java.util.\*;\):/* \1 */:
/\<theRetToken\>/ s:\(^.*$\):/* \1 */:
/\<_saveIndex\>/ s:\(^.*$\):/* \1 */:
/tryAgain:/,+2 s:\(^.*_token.*$\):/* \1 */:
