# Fix unreferenced imports
s:\(import antlr.TreeParser;\):/* \1 */:
s:\(import antlr.Token;\):/* \1 */:
s:\(import antlr.ANTLRException;\):/* \1 */:
s:\(import antlr.MismatchedTokenException;\):/* \1 */:
s:\(import antlr.SemanticException;\):/* \1 */:
s:\(import antlr.collections.impl.BitSet;\):/* \1 */:
s:\(import antlr.ASTPair;\):/* \1 */:
s:\(import antlr.collections.impl.ASTArray;\):/* \1 */:
