/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __com_redhat_ftk_CustomDrawingArea__
#define __com_redhat_ftk_CustomDrawingArea__

#include <jni.h>


#include "gtk/gtk.h"
#include "ftkcustomdrawingarea.h"
#include "jg_jnu.h"
#include "gtk_java.h"

#include "ftkcustomatkobject.h"

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jobject JNICALL 
Java_com_redhat_ftk_CustomDrawingArea_ftk_1custom_1drawing_1area_1new (JNIEnv *env, jclass cls){
  return getGObjectHandle(env, (GObject *) ftk_custom_drawing_area_new ());
}

JNIEXPORT void JNICALL
Java_com_redhat_ftk_CustomDrawingArea_ftk_1custom_1drawing_1area_1set_1accessible (JNIEnv *env,
										   jclass cls,
										   jobject drawingArea,
										   jobject atkObject){
  FtkCustomDrawingArea* widget = (FtkCustomDrawingArea*)getPointerFromHandle(env, drawingArea);
  FtkCustomAtkObject* accessible = (FtkCustomAtkObject*)getPointerFromHandle(env, atkObject);
  ftk_custom_drawing_area_set_accessible(widget, accessible);
}

#ifdef __cplusplus
}
#endif

#endif /* __com_redhat_ftk_CustomDrawingArea__ */
