#!/bin/sh

if [ "$1"x = "-logx" ] ; then
    LOGGING=FINEST
    if [ -n "$2" -a \( "$2" = "INFO" -o "$2" = "CONFIG" -o "$2" = "FINE" -o "$2" = "FINER" -o "$2" = "FINEST" \) ] ; then
	LOGGING=$2
    fi
elif [ -n "$1" ] ; then
	echo 'Usage $0 [-log [INFO|CONFIG|FINE|FINER|FINEST]]'
    exit
fi

if [ -n "$LOGGING" ] ; then
    LOGPROP=~/.frysk/logging.properties
# Save users logging.properties and create our own
    if [ -r $LOGPROP ] ; then
	if grep 'frysk logging properties.*Generated' $LOGPROP ; then
	    true
	else
	    mv $LOGPROP ${LOGPROP}.orig
	fi
    fi
# Keep this line in sync with above grep
    echo "# frysk logging properties.  Generated by $0" > $LOGPROP
    echo ".level = $LOGGING" >> $LOGPROP
fi

cat <<EOF
import junit.framework.TestSuite;
import junit.framework.TestResult;
import junit.framework.AssertionFailedError;
import junit.textui.ResultPrinter;
import junit.framework.Test;
import java.io.PrintStream;

public class TestRunner
    extends junit.textui.TestRunner
{
    TestRunner (ResultPrinter resultPrinter)
    {
	super (resultPrinter);
    }

    public static class Results
	extends ResultPrinter
    {
	// Does this have a race condition?
	boolean pass = false;
	public void startTest (Test test)
	{
	    System.out.print ("Running ");
	    System.out.print (test);
	    System.out.print (" ...");
	    System.out.flush ();
	    pass = true;
	}
	public void endTest (Test test)
	{
	    if (pass)
		System.out.println ("PASS");
	    else
		System.out.println ();
	}
	private void printProblem (String what, Throwable t)
        {
	    System.out.println (what);
	    System.out.print ("  ");
	    System.out.print (t);
        }

	public void addError (Test test, java.lang.Throwable t)
	{
	    printProblem ("ERROR", t);
	    pass = false;
	}
	public void addFailure (Test test, AssertionFailedError t)
	{
	    printProblem ("FAIL", t);
	    pass = false;
	}
	// Constructor.
	Results (PrintStream stream)
	{
	    super (stream);
	}
    }

    static Class[] testClasses = new Class[] {
EOF

for test in x "$@" ; do
    test ${test} = x && continue
    d=`dirname ${test}`
    b=`basename ${test} .java`
    class=`echo ${d}/${b} | tr '[/]' '[.]'`
    cat <<EOF
            ${class}.class,
EOF
done

cat <<EOF
	};
    public static void main (String[] args)
    {
	TestRunner runner = new TestRunner (new Results (System.out));
        TestSuite testSuite = new TestSuite ();
        int repeats = 1;
        if (args.length > 0) {
	    // Construct the testsuite from the list of names.
            for (int i = 0; i < args.length; i++) {
                if (args[i].charAt (0) == '-')
		    repeats = -Integer.parseInt (args[i]);
                else
                    testSuite.addTest (runner.getTest (args[i]));
            }
        }
        else {
	    for (int i = 0; i < testClasses.length; i++) {
                testSuite.addTest (new TestSuite (testClasses[i]));
            }
        }
        try {
	    for (int i = 0; i < repeats; i++) {
	        TestResult testResult = runner.doRun (testSuite);
	        if (!testResult.wasSuccessful()) 
		    System.exit (FAILURE_EXIT);
            }
	    System.exit(SUCCESS_EXIT);
	} catch(Exception e) {
	    System.err.println(e.getMessage());
	    System.exit (EXCEPTION_EXIT);
	}
    }
}
EOF
